# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
mod_version=1.0.0
mod_group=net.smackplays.smacksutil
java_version=21

# Common
minecraft_version=1.21.6
mod_name=SmacksUtil
mod_author=smackplays
mod_id=smacksutil
mod_license=C0-1.0
mod_credits=
mod_description=The description of your mod. \nAccepts multilines.

minecraft_version_range=[1.21.6]

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.6-20250617.151856
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft_version=1.21.5
parchment_mappings_version=2025.06.15


# Fabric
fabric_version=0.128.0+1.21.6
fabric_yarn_mappings=1.21.6+build.1
fabric_loader_version=0.16.14
fabric_loom_version=1.10-SNAPSHOT

# NeoForge
neoforge_version=21.6.15-beta
neoforge_loader_version_range=[21.6.15-beta,)

# Dependency options
modmenu_version=15.0.0-beta.3
cloth_config_version=19.0.147

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false