# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
mod_group=net.smackplays.smacksutil
java_version=21
# Common
minecraft_version=1.21.1
mod_name=SmacksUtil
mod_version=1.0.0
mod_author=smackplays
mod_id=smacksutil
mod_license=C0-1.0
mod_credits=
mod_description=The description of your mod. \nAccepts multilines.

minecraft_version_range=[1.21.1, 1.22)

# Fabric
fabric_version=0.105.0+1.21.1
fabric_loader_version=0.16.5

# Forge
forge_version=52.0.16
forge_version_range=[0,)
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.66
neoforge_version_range=[21.1.0,)
neoforge_loader_version_range=[4,)

# Dependency options
modmenu_version=11.0.2
cloth_config_version=15.0.130
trinkets_version=3.10.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false