# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Publish on CurseForge [Forge & Fabric & NeoForge]
on: [ workflow_dispatch ]
env: #Environment variables that can later be referenced using ${{ env.MINECRAFT_VERSION }}. These are useful for repeating information and allow for quick changes for new mod updates
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17
  VERSION: 0.0.14
  RELEASE_NAME: SmackUtil-1.20.4-0.0.14

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
        # and run on both Linux and Windows
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts fabric
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: Fabric Artifacts
          path: fabric/build/libs/
      - name: capture build artifacts forge
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: Forge Artifacts
          path: forge/build/libs/
      - name: publish (CurseForge Fabric)
        if: ${{ runner.os == 'Linux' && matrix.java == '21' && github.event_name == 'workflow_dispatch'}} # Only upload artifacts built from latest java on one OS
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 952860                                             #The id of your CurseForge project
          curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

          name: SmacksUtil Fabric ${{ env.VERSION }} for MC 1.20.4
          version: smacksutil-fabric-1.20.4-${{ env.VERSION }}
          version-type: beta
          changelog-file: CHANGELOG.*

          files: |
            fabric/build/libs/*.jar

          loaders: |
            fabric

          game-versions: |
            1.20.4

      - name: publish (CurseForge Forge)
        if: ${{ runner.os == 'Linux' && matrix.java == '21' && github.event_name == 'workflow_dispatch'}} # Only upload artifacts built from latest java on one OS
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 952860                                             #The id of your CurseForge project
          curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

          name: SmacksUtil Forge ${{ env.VERSION }} for MC 1.20.4
          version: smacksutil-forge-1.20.4-${{ env.VERSION }}
          version-type: beta
          changelog-file: CHANGELOG.*

          files: |
            forge/build/libs/*.jar

          loaders: |
            forge

          game-versions: |
            1.20.4

      - name: publish (CurseForge NeoForge)
        if: ${{ runner.os == 'Linux' && matrix.java == '21' && github.event_name == 'workflow_dispatch'}} # Only upload artifacts built from latest java on one OS
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 952860                                             #The id of your CurseForge project
          curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

          name: SmacksUtil NeoForge ${{ env.VERSION }} for MC 1.20.4
          version: smacksutil-neoforge-1.20.4-${{ env.VERSION }}
          version-type: beta
          changelog-file: CHANGELOG.*

          files: |
            neoforge/build/libs/*.jar

          loaders: |
            neoforge

          game-versions: |
            1.20.4
