on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release_1.20.4_V*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2